"""Figures are regenerated by code, and the committed ones exist.

This does NOT compare pixels. A PNG drawn on a Linux runner is never byte-identical to one
drawn on a laptop (fonts, antialiasing), so a pixel test here would be red on correct
behaviour. The pixel comparison with the manuscript is in results/reproduction_report.md,
measured once and stated as such. Maps (Figures 1-2) need cartopy and a network, so CI
exercises them through scripts/run_all.py rather than here.
"""
from __future__ import annotations

import pytest
from PIL import Image

from dcbtm import figures

COMMITTED = ["fig1_us_texas_datacenters.png", "fig1_us_texas_datacenters.pdf", "fig2_global_datacenters.png",
             "fig2_global_datacenters.pdf", "fig4_demand_monte_carlo.png", "fig5_scenario_dispatch.png",
             "fig6_asset_utilization.png"]


@pytest.mark.parametrize("name", COMMITTED)
def test_committed_figure_exists(paths, name):
    p = paths.figures / name
    assert p.is_file() and p.stat().st_size > 10_000, name


def test_figures_4_to_6_regenerate(tmp_path, stages, cfg):
    made = [figures.figure4(stages["bands"], cfg, tmp_path),
            figures.figure5(stages["dispatch"], cfg, tmp_path),
            figures.figure6(stages["table13"], tmp_path)]
    for p in made:
        w, h = Image.open(p).size
        assert w > 1000 and h > 1000, (p.name, w, h)
